import React from "react";
import { FaTimes, FaDownload, FaSun, FaCheckCircle, FaPrint, FaFileContract } from "react-icons/fa";

const ReportModal = ({ isOpen, onClose, stats, elevation, azimuth, scenePreset }) => {
  if (!isOpen) return null;

  const annualKwh = Math.round(stats.rooftopArea * 1550 * 0.20 * 0.82);
  const monthlySavings = Math.round((annualKwh * 0.15) / 12);
  const npv25 = "$" + (monthlySavings * 12 * 18.5).toLocaleString();
  const co2Tons = ((annualKwh * 0.85) / 2204.62).toFixed(1);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md">
      <div className="w-full max-w-2xl bg-[#0e0e0e] border border-white/20 rounded-3xl p-6 sm:p-8 shadow-[0_20px_70px_rgba(0,0,0,0.95)] relative text-white max-h-[90vh] overflow-y-auto">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-6 right-6 p-2 rounded-xl bg-white/5 hover:bg-white/15 text-zinc-300 hover:text-white transition-colors border border-white/10">
          <FaTimes className="w-4 h-4" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/10">
          <div className="w-10 h-10 rounded-2xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center">
            <FaSun className="w-5 h-5 text-amber-400" />
          </div>
          <div>
            <span className="text-[10px] font-mono text-amber-400 uppercase tracking-widest block font-bold">
              OFFICIAL SOLAR FEASIBILITY AUDIT
            </span>
            <h2 className="text-[22px] sm:text-[26px] font-extrabold font-sans text-white tracking-tight">
              SunMap Architectural Summary
            </h2>
          </div>
        </div>

        {/* Audit Meta Details */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 mb-6 text-center font-mono text-[11px]">
          <div className="p-3 rounded-xl bg-white/[0.03] border border-white/5">
            <span className="text-zinc-500 block text-[10px] mb-0.5">TOPOLOGY</span>
            <span className="text-white font-bold uppercase">{scenePreset}</span>
          </div>
          <div className="p-3 rounded-xl bg-white/[0.03] border border-white/5">
            <span className="text-zinc-500 block text-[10px] mb-0.5">ROOF AREA</span>
            <span className="text-white font-bold">{stats.rooftopArea} m²</span>
          </div>
          <div className="p-3 rounded-xl bg-white/[0.03] border border-white/5">
            <span className="text-zinc-500 block text-[10px] mb-0.5">SOLAR ARRAY</span>
            <span className="text-white font-bold">{stats.panelsCount} Modules</span>
          </div>
          <div className="p-3 rounded-xl bg-white/[0.03] border border-white/5">
            <span className="text-zinc-500 block text-[10px] mb-0.5">EFFICIENCY</span>
            <span className="text-emerald-400 font-bold">82.4% PR</span>
          </div>
        </div>

        {/* Detailed Assessment Matrix */}
        <div className="space-y-3 p-4 rounded-2xl bg-white/[0.02] border border-white/10 font-mono text-[12px] mb-6">
          <div className="flex justify-between py-1 border-b border-white/5">
            <span className="text-zinc-400">Estimated Annual Energy Yield:</span>
            <span className="text-white font-bold">{annualKwh.toLocaleString()} kWh / year</span>
          </div>
          <div className="flex justify-between py-1 border-b border-white/5">
            <span className="text-zinc-400">Estimated Monthly Electric Offset:</span>
            <span className="text-emerald-400 font-bold">${monthlySavings.toLocaleString()} / month</span>
          </div>
          <div className="flex justify-between py-1 border-b border-white/5">
            <span className="text-zinc-400">Cumulative 25-Year Net Savings (NPV):</span>
            <span className="text-amber-400 font-bold">{npv25}</span>
          </div>
          <div className="flex justify-between py-1">
            <span className="text-zinc-400">Carbon Abatement Potential:</span>
            <span className="text-emerald-400 font-bold">{co2Tons} Metric Tons CO₂ / year</span>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-between pt-2">
          <span className="text-[11px] font-mono text-zinc-500">
            Generated by SunMap 3D Simulation Platform
          </span>
          <div className="flex gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white text-black font-mono font-bold text-[12px] hover:bg-amber-400 transition-colors">
              <FaPrint className="w-3.5 h-3.5" /> PRINT REPORT
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;
