import React from "react";
import { X, Printer, ShieldCheck } from "lucide-react";

const ReportModal = ({ isOpen, onClose, stats = {}, elevation = 45, azimuth = 180, scenePreset = "commercial" }) => {
  if (!isOpen) return null;

  const area = stats.totalRooftopArea || 210;
  const panels = stats.panelsCount || 120;
  const kw = (panels * 0.4).toFixed(1);
  const annualKwh = Math.round(area * 1850 * 0.20 * 0.82);
  const annualSavings = Math.round(annualKwh * 0.16);
  const grossCapex = Math.round(kw * 1000 * 2.80);
  const netCapex = Math.round(grossCapex * 0.70);
  const payback = (netCapex / annualSavings).toFixed(1);
  const co2 = ((annualKwh * 0.85) / 2204.62).toFixed(1);

  return (
    <div style={{
      position: "fixed",
      inset: 0,
      zIndex: 1000,
      background: "rgba(0, 0, 0, 0.85)",
      backdropFilter: "blur(12px)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px"
    }}>
      <div style={{
        background: "#0c111d",
        border: "1px solid rgba(255, 255, 255, 0.18)",
        borderRadius: "28px",
        width: "100%",
        maxWidth: "760px",
        padding: "32px",
        color: "#ffffff",
        position: "relative",
        maxHeight: "90vh",
        overflowY: "auto",
        boxShadow: "0 25px 80px rgba(0,0,0,0.9)",
        fontFamily: "monospace"
      }}>
        <button
          onClick={onClose}
          style={{
            position: "absolute",
            top: "24px",
            right: "24px",
            background: "rgba(255, 255, 255, 0.05)",
            border: "1px solid rgba(255, 255, 255, 0.1)",
            color: "#ffffff",
            padding: "8px",
            borderRadius: "10px",
            cursor: "pointer"
          }}>
          <X size={16} />
        </button>

        <div style={{ borderBottom: "1px solid rgba(255, 255, 255, 0.1)", paddingBottom: "20px", marginBottom: "24px" }}>
          <span style={{ fontSize: "0.72rem", color: "#f59e0b", letterSpacing: "0.1em", textTransform: "uppercase", fontWeight: 700 }}>
            SOLAR FEASIBILITY AUDIT
          </span>
          <h2 style={{ fontSize: "1.6rem", fontWeight: 800, margin: "4px 0 0 0", fontFamily: "sans-serif" }}>
            Engineering &amp; Financial Simulation Report
          </h2>
          <span style={{ fontSize: "0.75rem", color: "#64748b" }}>CAD Geometry: {scenePreset.toUpperCase()} • Generated by SunMap 3D</span>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", marginBottom: "20px" }}>
          <div style={{ background: "rgba(255, 255, 255, 0.02)", padding: "16px", borderRadius: "16px", border: "1px solid rgba(255, 255, 255, 0.06)" }}>
            <span style={{ color: "#64748b", fontSize: "0.72rem", display: "block" }}>RECOMMENDED SYSTEM CAPACITY</span>
            <span style={{ fontSize: "1.4rem", fontWeight: 800, color: "#f59e0b" }}>{kw} kWp</span>
            <span style={{ fontSize: "0.72rem", color: "#94a3b8", display: "block" }}>{panels} Monocrystalline PV Modules</span>
          </div>

          <div style={{ background: "rgba(255, 255, 255, 0.02)", padding: "16px", borderRadius: "16px", border: "1px solid rgba(255, 255, 255, 0.06)" }}>
            <span style={{ color: "#64748b", fontSize: "0.72rem", display: "block" }}>ANNUAL CLEAN ENERGY GENERATION</span>
            <span style={{ fontSize: "1.4rem", fontWeight: 800, color: "#10b981" }}>{annualKwh.toLocaleString()} kWh/yr</span>
            <span style={{ fontSize: "0.72rem", color: "#94a3b8", display: "block" }}>Based on 8,760 hourly solar vectors</span>
          </div>
        </div>

        <div style={{ background: "rgba(255, 255, 255, 0.02)", padding: "16px", borderRadius: "16px", border: "1px solid rgba(255, 255, 255, 0.06)", display: "flex", flexDirection: "column", gap: "12px", marginBottom: "24px" }}>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ color: "#94a3b8" }}>Net Turnkey Installation Capex (30% ITC applied):</span>
            <strong style={{ color: "#ffffff" }}>${netCapex.toLocaleString()}</strong>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ color: "#94a3b8" }}>Estimated Year 1 Utility Revenue Offset:</span>
            <strong style={{ color: "#10b981" }}>${annualSavings.toLocaleString()}/yr</strong>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ color: "#94a3b8" }}>Projected Simple Payback Horizon:</span>
            <strong style={{ color: "#f59e0b" }}>{payback} Years</strong>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ color: "#94a3b8" }}>Lifetime 25-Year Cumulative Carbon Abatement:</span>
            <strong style={{ color: "#ffffff" }}>{(parseFloat(co2) * 25).toFixed(0)} Metric Tons CO₂</strong>
          </div>
        </div>

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "6px", color: "#10b981", fontSize: "0.78rem" }}>
            <ShieldCheck size={16} />
            <span>NREL PVLib Benchmarked &amp; CityGML Compliant</span>
          </div>

          <div style={{ display: "flex", gap: "10px" }}>
            <button
              onClick={() => window.print()}
              style={{
                display: "flex",
                alignItems: "center",
                gap: "6px",
                padding: "10px 18px",
                borderRadius: "12px",
                background: "rgba(255, 255, 255, 0.05)",
                border: "1px solid rgba(255, 255, 255, 0.15)",
                color: "#ffffff",
                fontSize: "0.82rem",
                fontWeight: 700,
                cursor: "pointer"
              }}>
              <Printer size={14} />
              <span>Print Audit</span>
            </button>

            <button
              onClick={onClose}
              style={{
                padding: "10px 22px",
                borderRadius: "12px",
                background: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
                border: "none",
                color: "#ffffff",
                fontSize: "0.82rem",
                fontWeight: 700,
                cursor: "pointer"
              }}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;
